# Generated by Django 3.0.6 on 2021-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
