# Generated by Django 3.0.6 on 2021-02-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0004_auto_20210203_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
