# Generated by Django 3.0.6 on 2021-02-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0008_auto_20210203_0833'),
        ('paradise', '0002_remove_orderproduct_user'),
    ]

    operations = [
    ]
